### ISSUE TITLE
Add Component diagram (C3) for Rentals service

### ISSUE THREAD

**Issue by krzysztofzajaczkowski** [e-library-on-containers/e-library-on-containers#5]
**As a** developer,
**I want** to have a Component diagram for Rentals service with some description
**so that** other maintainers and myself have knowledge about service workflow and an agreement about its relations to other services.

**Comment by krzysztofzajaczkowski** [comment]
Couple of typos, suggestions below:
`append only database`*
`Rentals READ repository is a projection, built by Rentals worker from aggregated events, that facilitates reading from the database`*

**Comment by RafKulas** [comment]
Sorry, my bad, IntelliJ registered proper version *append only database* as typo 😆 
![image](https://user-images.githubusercontent.com/50609857/202865384-93dd4246-c56d-410b-ae73-b712f04df2a5.png)
